name:                gribbler
version:             0.1.0.0
github:              "LStandman/gribbler"
license:             GPL-3.0-or-later
author:              "LStandman"
maintainer:          "65296484+LStandman@users.noreply.github.com"
copyright:           "2022-2023 LStandman"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/LStandman/gribbler#README.md>

dependencies:
- base >= 4.7 && < 5
- array

library:
  source-dirs:
  - gribbler

executables:
  gribbler-exe:
    main:                app/Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gribbler

tests:
  gribbler-test:
    main:                tests/Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gribbler
