module Main where

import BNF
import YAML

main :: IO ()
main = do
  --print (esc_char "\r\nasdf")
  --print (esc_char "\\xaasdf")
  --print (esc_char "\\nabasdf")
  --print (esc_char "xabasdf")
  print $ match_char 'c' ("carl", 0, 0)
  print $ match_char 'c' ("xarl", 0, 0)
  print $ zom (match_char 'c') ("xarl", 0, 0)
  print $ zom (match_char 'c') ("carl", 0, 0)
  print $ zom (match_char 'c') ("ccrl", 0, 0)
  print $ oom (match_char 'c') ("xarl", 0, 0)
  print $ oom (match_char 'c') ("carl", 0, 0)
  print $ oom (match_char 'c') ("ccrl", 0, 0)
  print $ zoo (match_char 'c') ("xarl", 0, 0)
  print $ zoo (match_char 'c') ("carl", 0, 0)
  print $ zoo (match_char 'c') ("ccrl", 0, 0)
  print $ b_break ("\n\rccrl", 0, 0)
  print $ b_break ("\n\nccrl", 0, 0)
  print $ b_break ("\r\rccrl", 0, 0)
  print $ b_break ("\r\nccrl", 0, 0)
  print $ b_break ("ccrl", 0, 0)
  print $ nb_char ("ccrl", 0, 0)
  print $ nb_char ("\ncrl", 0, 0)
  print $ c_printable ("carl", 0, 0)
  print $ c_printable ("\x85\&arl", 0, 0)
  print $ ns_uri_char ("%AFxxxx", 0, 0)
  print $ ns_uri_char ("%AGxxxx", 0, 0)
  print $ b_as_line_feed ("\n\rccrl", 0, 0)
  print $ b_as_line_feed ("\n\nccrl", 0, 0)
  print $ b_as_line_feed ("\r\rccrl", 0, 0)
  print $ b_as_line_feed ("\r\nccrl", 0, 0)
  print $ c_ns_esc_char ("\\\x09", 0, 0)
  print $ c_ns_esc_char ("\\U00000041", 0, 0)
  print $ s_indent  1 ("   \n\n  as\n  space", 0, 0)
  print $ b_l_folded BlockOut 10 ("\n  \n \n\n  as\n  space", 0, 0)
  print ("\x85", 0, 0)
  print $ c_single_quoted BlockKey 0 ("'implicit block key'", 0, 0)
